name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to VPS using SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: './dist/*'
          remote_path: '/var/www/blockbuster'
          sftpArgs: '-o ServerAliveInterval=60'